spring.application.name=gc-career-studio-backend
server.port=8085

spring.datasource.url=jdbc:postgresql://dpg-dadrcfuq1p3s73et2qtg-a.singapore-postgres.render.com:5432/gc_career_studio_db
spring.datasource.username=gc_career_studio_db_user
spring.datasource.password=BxrU34WpG4wSIA5jsGDJstfoWDPeFQBs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true